_target_: src.policies.mappo.MAPPO
params:
  n_layers: 2
  hidden_dim: 64
  learning_rate: 0.0003
  gamma: 0.99
  gae_lambda: 0.95
  gae: True
  n_agents: 3
  ent_coef: 0.01
  vf_coef: 0.5
  norm_adv: True
  clip_coef: 0.2
  clip_vloss: True
  max_grad_norm: 2
  target_kl: null
  update_epochs: 5
  num_minibatches: 1
  rollout_threads: 64
  env_steps: 25
  activation: relu