_target_: src.runner.PGRunner
params:
  total_timesteps: 20_000_000
  rollout_threads: 64
  env_steps: 25
  lr_decay: True
  n_agents: 3
  eval_episodes: 100
  checkpoint_dir: null
  save_dir: $SCRATCH/saf/$SLURM_JOB_ID/
  comet:
    project_name: corl
