_target_: src.runner.PGRunner
params:
  total_timesteps: 20_000_000
  rollout_threads: ${rollout_threads}
  env_steps: ${env_steps}
  lr_decay: True
  n_agents: ${n_agents}
  eval_episodes: 100
  checkpoint_dir: null
  save_dir: $SCRATCH/saf/$SLURM_JOB_ID/
  comet:
    project_name: corl