_target_: src.runner.PGRunner
params:
  total_timesteps: 10_000_000
  rollout_threads: ${rollout_threads}
  env_steps: ${env_steps}
  lr_decay: True
  n_agents: ${n_agents}
  eval_episodes: 32
  checkpoint_dir: null
  experiment_name: ${experiment_name}
  save_dir: $SCRATCH/saved_model/${experiment_name}/
  latent_kl: ${latent_kl}
  comet:
    project_name: corl
    experiment_name: ${experiment_name}